import keyMirrorRecursive from "fbjs/lib/keyMirrorRecursive";

export const pageName = "CompanyMasterPage";

export const stateNameList = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
];
// export const stateNameList = [
//   {title :  "Andaman and Nicobar Islands"},
//   {title : "Andhra Pradesh"},
//   {title : "Arunachal Pradesh"},
//   {title : "Assam"},
//   {title : "Bihar"},
//   {title : "Chandigarh"},
//   {title : "Chhattisgarh"},
//   {title : "Dadra and Nagar Haveli"},
//   {title : "Daman and Diu"},
//   {title : "Delhi"},
//   {title : "Goa"},
//   {title : "Gujarat"},
//   {title : "Haryana"},
//   {title : "Himachal Pradesh"},
//   {title : "Jammu and Kashmir"},
//   {title : "Jharkhand"},
//   {title : "Karnataka"},
//   {title : "Kerala"},
//   {title : "Ladakh"},
//   {title : "Lakshadweep"},
//   {title : "Madhya Pradesh"},
//   {title : "Maharashtra"},
//   {title : "Manipur"},
//   {title : "Meghalaya"},
//   {title : "Mizoram"},
//   {title : "Nagaland"},
//   {title : "Odisha"},
//   {title : "Puducherry"},
//   {title : "Punjab"},
//   {title : "Rajasthan"},
//   {title : "Sikkim"},
//   {title : "Tamil Nadu"},
//   {title : "Telangana"},
//   {title : "Tripura"},
//   {title : "Uttar Pradesh"},
//   {title : "Uttarakhand"},
//   {title : "West Bengal"},
// ];

export const ActionTypes = keyMirrorRecursive(
    {
        CLASS_DTO: undefined,
        RESET_DATA: undefined,
        RESPONSE_DTO: undefined,
        ADD_COMPANY_REQUEST: undefined,
        ADD_COMPANY_RESPONSE: undefined,
        MODEL_OPEN_REQUEST:undefined,
        COMPANY_LIST_REQUEST:undefined,
        COMPANY_LIST_RESPONSE:undefined,
        OPEN_EDIT_MODEL:undefined,
        DELETE_COMPANY:undefined,
    },
    pageName
);
