import keyMirrorRecursive from "fbjs/lib/keyMirrorRecursive";

export const pageName = "ExpenseMasterPage";

export const stateNameList = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
];
// export const stateNameList = [
//   {value :  "Andaman and Nicobar Islands",display :  "Andaman and Nicobar Islands"},
//   {value : "Andhra Pradesh",display : "Andhra Pradesh"},
//   {value : "Arunachal Pradesh",display : "Arunachal Pradesh"},
//   {value : "Assam",display : "Assam"},
//   {value : "Bihar",display : "Bihar"},
//   {value : "Chandigarh",display : "Chandigarh"},
//   {value : "Chhattisgarh",display : "Chhattisgarh"},
//   {value : "Dadra and Nagar Haveli",display : "Dadra and Nagar Haveli"},
//   {value : "Daman and Diu",display : "Daman and Diu"},
//   {value : "Delhi"},
//   {value : "Goa"},
//   {value : "Gujarat"},
//   {value : "Haryana"},
//   {value : "Himachal Pradesh"},
//   {value : "Jammu and Kashmir"},
//   {value : "Jharkhand"},
//   {value : "Karnataka"},
//   {value : "Kerala"},
//   {value : "Ladakh"},
//   {value : "Lakshadweep"},
//   {value : "Madhya Pradesh"},
//   {value : "Maharashtra"},
//   {value : "Manipur"},
//   {value : "Meghalaya"},
//   {value : "Mizoram"},
//   {value : "Nagaland"},
//   {value : "Odisha"},
//   {value : "Puducherry"},
//   {value : "Punjab"},
//   {value : "Rajasthan"},
//   {value : "Sikkim"},
//   {value : "Tamil Nadu"},
//   {value : "Telangana"},
//   {value : "Tripura"},
//   {value : "Uttar Pradesh"},
//   {value : "Uttarakhand"},
//   {value : "West Bengal"},
// ];

export const ActionTypes = keyMirrorRecursive(
    {
        CLASS_DTO: undefined,
        RESET_DATA: undefined,
        RESPONSE_DTO: undefined,
        ADD_COMPANY_REQUEST: undefined,
        ADD_COMPANY_RESPONSE: undefined,
        MODEL_OPEN_REQUEST:undefined,
        COMPANY_LIST_REQUEST:undefined,
        COMPANY_LIST_RESPONSE:undefined,
        OPEN_EDIT_MODEL:undefined,
        DELETE_COMPANY:undefined,
        COMPANY_NAME_LIST_REQUEST:undefined,
        COMPANY_NAME_LIST_RESPONSE:undefined,

        ADD_EXPENSE_REQUEST:undefined,
        ADD_EXPENSE_RESPONSE:undefined,

        ADD_EXPENSE_CATEGORY_REQUEST:undefined,
        ADD_EXPENSE_CATEGORY_RESPONSE:undefined,

        EXPENSE_LIST_REQUEST:undefined,
        EXPENSE_LIST_RESPONSE:undefined,

        EXPENSE_CATEGORY_LIST_REQUEST:undefined,
        EXPENSE_CATEGORY_LIST_RESPONSE:undefined,

        EXPENSE_CATEGORY_NAME_LIST_REQUEST:undefined,
        EXPENSE_CATEGORY_NAME_LIST_RESPONSE:undefined,
    },
    pageName
);
